spring:
  profiles:
    active:
      - h2
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false

endpoints:
  sensitive: false

management:
  security:
    enabled: false

rate:
  service:
    url: http://www.cbr.ru/scripts/XML_daily.asp
